Rails.application.routes.draw do
  get 'payments/new'
  get 'payments/view'
  get 'payments/plan_each'
  post 'payments/plan_all'
  get 'payments/services_each'
  post 'payments/services_all'
  get 'payments/edit'
  get 'payments/show'
  resources :payments
  get 'contracts/main'
  get 'contracts/new'
  get 'contracts/view'
  get 'contracts/show'
  get 'contracts/edit'
  get 'contracts/all'
  resources :contracts
  get 'contragents/del'
  get 'contragents/main'
  get 'contragents/view'
  get 'contragents/edit'
  get 'contragents/dump'
  resources :contragents
  get 'orgs/del'
  get 'orgs/main'
  get 'orgs/view'
  get 'orgs/dump'
  get 'orgs/contracts'
  get 'orgs/edit'
  resources :orgs
  get 'main/index'
  root 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
