Rails.application.routes.draw do
  get 'contracts/main'
  get 'contracts/new'
  get 'contracts/pay'
  get 'contracts/payments'
  get 'contracts/view'
  get 'contracts/view_each'
  get 'contracts/edit'
  get 'contracts/all'
  get 'contragents/main'
  get 'contragents/new'
  get 'contragents/view'
  get 'contragents/view_each'
  get 'contragents/edit'
  get 'contragents/dump'
  get 'org/main'
  get 'org/new'
  get 'org/view'
  get 'org/dump'
  get 'org/contracts'
  get 'org/view_each'
  get 'org/edit'
  get 'main/index'
  root 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
